name: CI on Tag

on:
  push:
    tags: '*'
        
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: validate
        run: dapper ci

  create-release:
    runs-on: ubuntu-latest
    needs:
      - validate
    permissions:
      contents: write # needed for creating the GH release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: (for testing) check files
        run: ls -l /tmp/assets
      - name: Create GH release
        run: |
          if [[ ${{ github.ref_name }} == *"rc"*  || ${{ github.ref_name }} == *"alpha"* ]]; then
            gh release create ${{ github.ref_name }} --verify-tag --prerelease --generate-notes 
          else
            gh release create ${{ github.ref_name }} --verify-tag --generate-notes --latest
          fi